# Languages
# Documentation: https://docs.hugoblox.com/reference/language/

en:
  languageCode: en-us
  contentDir: content/en/
  title: "Biostatistics edu"
  params:
    description: "Personal site of Maicel Monzón"
  menu:
    main:
      - name: Bio
        url: /
        weight: 10
      - name: Papers
        url: /#papers
        weight: 11
      - name: Talks
        url: /#talks
        weight: 12
      # - name: News
      #   url: /#news
        weight: 13
      - name: Experience
        url: experience/
        weight: 20
      - name: Projects
        url: /projects/
        weight: 30
      - name: Teaching
        url: /teaching/
        weight: 40
      - name: Blog
        url: /post/ # no funciona al hacerl clic sobre el
        weight: 50
        identifier: blog  # Identificador único para el padre
      #   has_children: true  # ¡Agregado! Fuerza el dropdown
      - name: "See All Articles" # ¡NUEVO HIJO!
        url: /post/ # Este enlace SIEMPRE funcionará
        weight: 51 # Aparece primero en el submenú
        parent: blog
      # Usar un texto claro mejora la UX, guiando al usuario.     
      - name: "Health Statistics"
        url: /categories/estadistica-en-salud/
        weight: 52
        parent: blog  # Referencia al identificador del padre
      - name: "Research Methodology"
        url: /categories/metodologia-de-investigacion/
        weight: 54
        parent: blog
      - name: "Regulatory Assessment"
        url: /categories/evaluacion-regulatoria/
        weight: 56
        parent: blog
      - name: "Practical Code in R or Python"
        url: /categories/codigo-practico-en-r-o-python/  # ¡Corregido! Agregado -python
        weight: 58
        parent: blog
      - name: "Critical Reflections"
        url: /categories/reflexiones-criticas/
        weight: 60  # ¡Corregido! Peso único para orden
        parent: blog
      # - name: Blog
      #   url: /post/
        # weight: 50
      - name: "Subscribe"
        url: /subscribe/
        weight: 80 # Un número alto para que aparezca al final
      - name: "Collaborations"
        url: /collaborations/
        weight: 90  # Un número alto para que aparezca al final


es:
  languageCode: es-es
  contentDir: content/es/
  title: "Bioestadística edu"
  params:
    description: "Sitio personal de Maicel Monzón"
  menu:
    main:
      - name: Biografía
        url: /
        weight: 10
      - name: Publicaciones
        url: /#papers
        weight: 11
      - name: Conferencias
        url: /#talks
        weight: 12
      # - name: Noticias
      #   url: /#news
        weight: 13
      - name: Experiencia
        url: /experience/
        weight: 20
      - name: Diapositivas
        url: /slides/
        weight: 30
      - name: Proyectos
        url: /projects/
        weight: 40
      - name: Docencia
        url: /teaching/
        weight: 50
      - name: Blog
        url: /post/ # no funciona al hacerl clic sobre el
        weight: 60
        identifier: blog  # Identificador único para el padre
      #   has_children: true  # ¡Agregado! Fuerza el dropdown
      - name: "Ver Todos los Artículos" # ¡NUEVO HIJO!
        url: /post/ # Este enlace SIEMPRE funcionará
        weight: 61 # Aparece primero en el submenú
        parent: blog
      # Usar un texto claro mejora la UX, guiando al usuario.     
      - name: "Estadística en Salud"
        url: /categories/estadistica-en-salud/
        weight: 62
        parent: blog  # Referencia al identificador del padre
      - name: "Metodología de Investigación"
        url: /categories/metodologia-de-investigacion/
        weight: 64
        parent: blog
      - name: "Evaluación Regulatoria"
        url: /categories/evaluacion-regulatoria/
        weight: 66
        parent: blog
      - name: "Código Práctico en R/Python"
        url: /categories/codigo-practico-en-r-o-python/  # ¡Corregido! Agregado -python
        weight: 68
        parent: blog
      - name: "Reflexiones Críticas"
        url: /categories/reflexiones-criticas/
        weight: 70  # ¡Corregido! Peso único para orden
        parent: blog
      - name: "Suscríbete"
        url: /subscribe/
        weight: 80  # Un número alto para que aparezca al final
      - name: "Colaboraciones"
        url: /collaborations/
        weight: 90  # Un número alto para que aparezca al final

# # Español (idioma por defecto)
# es:
#   languageCode: es-es
#   weight: 1
#   contentDir: content/
#   title: "Maicel Monzón"
#   params:
#     description: "Sitio personal de Maicel Monzón"
# 
# # Inglés
# en:
#   languageCode: en-us
#   weight: 2
#   contentDir: content/
#   title: "Maicel Monzon"
#   params:
#     description: "Personal website of Maicel Monzon"
# 

# # Languages
# #   Create a section for each of your site's languages.
# #   Documentation: https://docs.hugoblox.com/reference/language/
# 
# # Default language
# en:
#   languageCode: en-us
#   # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
#   # contentDir: content/en
# 
# # Uncomment the lines below to configure your website in a second language.
# #es:
#  # languageCode: es-es
#  # contentDir: content/es
#  # title: Bioestadística edu
#  # params:
#  #   description: Sitio personal de maicel monzón
#  # menu:
#  #   main:
#  #     - name: 传
#  #       url: '#about'
#  #       weight: 1
